version: "3.5"

services:
  lumen:
    ports:
      - "8182:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: php -S lumen:8000 -t public
    restart: always
    depends_on:
      - db
      - redis-server
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: LIS_MOBILE_PCR
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"